add_newline = true

format="""
╭─ $time \
$username\
[@](#ffffff bold)\
[archlinux](#00ffff bold) \
$directory \
$git_branch \
$git_status
╰─$character
"""
#λ
#➤
#α
right_format = "$status $conda"

[character]
success_symbol = "[➤](white)"
error_symbol = "[➤](white)"

[time]
disabled = false
use_12hr = true
format = '[$time](#cccccc bold)'
time_format = '%I:%M'

[username]
disabled = false
show_always = true
format = "[$user](#00ffff bold)"

[hostname]
ssh_only = false
disabled = false

[os]
format = "[$name](#00ffff bold)"
disabled = false

[os.symbols]
EndeavourOS = " "

[directory]
disabled = false
truncate_to_repo = true
truncation_length = 5
truncation_symbol = ".../"
format = "[  $path](#cccccc)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[git_branch]
symbol = " "
format = "[$symbol$branch](#cccccc bold)"

[git_status]
format = "[$all_status$ahead_behind](#cccccc bold)"

[status]
symbol = '↵ '
sigint_symbol = "user "
format = "[$symbol$status](red)"
map_symbol = true
disabled = false

[conda]
symbol = " "
format ="[$symbol$environment](bold green) "

