[window]

dimensions.columns = 127
dimensions.lines = 27

title = "Alacritty"
dynamic_title = false

opacity = 0.5

padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"

size = 10.0

[cursor]

blink_interval = 600
unfocused_hollow = false

[cursor.style]

shape   = "Beam"
blinking= "Always"

[colors]

draw_bold_text_with_bright_colors = true

[colors.normal]

black   = "#000000"
blue    = "#0000CD"
cyan    = "#00CDCD"
green   = "#00CD00"
magenta = "#CD00CD"
red     = "#CD0000"
white   = "#FAEBD7"
yellow  = "#CDCD00"

[colors.bright]

black	= "#404040"
red	    = "#FF0000"
green	= "#00FF00"
yellow	= "#FFFF00"
blue	= "#0000FF"
magenta = "#FF00FF"
cyan 	= "#00FFFF"
white	= "#FFFFFF"

[colors.dim]

black	= "#000000"
red	    = "#872B22"
green	= "#549E4E"
yellow	= "#AAAB34"
blue	= "#0F2353"
magenta	= "#972596"
cyan	= "#31A7A6"
white	= "#E3C7A1"

[colors.primary]

background = "#000000"
foreground = "#FFFFFF"
dim_foreground = "None"

[colors.search.focused_match]

background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]

background = "CellBackground"
foreground = "CellForeground"

[colors.selection]

background = "CellForeground"
text       = "CellBackground"

[colors.hints.end]

background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]

background = "CellBackground"
foreground = "CellForeground"


[mouse]

hide_when_typing = true

[keyboard]

bindings = [
    { key = "N", mods = "Control", action = "CreateNewWindow" },
]
